/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl

import org.eclipse.xtext.scoping.impl.DefaultGlobalScopeProvider
import org.eclipse.xtext.resource.IResourceDescription
import com.google.inject.Inject
import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.emf.ecore.EReference
import org.eclipse.xtext.scoping.IScope

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
	
	override bindIGlobalScopeProvider() {
		MyDslGlobalScopeProvider
	}
	
}
